"""Initial schema

Revision ID: ff584073c694
Revises: 
Create Date: 2026-09-30 17:36:07.117875+05:30
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ff584073c694'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_day',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dow', sa.SmallInteger(), nullable=False),
    sa.Column('dow_name', sa.String(length=3), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('iso_year', sa.SmallInteger(), nullable=False),
    sa.Column('iso_week', sa.SmallInteger(), nullable=False),
    sa.Column('is_payday', sa.Boolean(), nullable=False),
    sa.Column('festival', sa.String(length=24), nullable=True),
    sa.Column('festival_ramp', sa.Numeric(precision=3, scale=1, asdecimal=False), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('monsoon', sa.Boolean(), nullable=False),
    sa.Column('is_operating', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_calendar_day'))
    )
    op.create_table('case_type',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('brand', sa.String(length=8), nullable=False),
    sa.Column('temp', sa.String(length=8), nullable=False),
    sa.Column('kg', sa.Numeric(precision=7, scale=2, asdecimal=False), nullable=False),
    sa.Column('m3', sa.Numeric(precision=7, scale=4, asdecimal=False), nullable=False),
    sa.Column('load_rank', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_case_type'))
    )
    op.create_table('district',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('depot', sa.String(length=16), nullable=False),
    sa.Column('road_class', sa.String(length=16), nullable=False),
    sa.Column('free_flow_kmh', sa.Numeric(precision=6, scale=1, asdecimal=False), nullable=False),
    sa.Column('depot_to_district_km', sa.Numeric(precision=7, scale=1, asdecimal=False), nullable=False),
    sa.Column('depot_to_district_min', sa.Integer(), nullable=False),
    sa.Column('inter_stop_km', sa.Numeric(precision=6, scale=1, asdecimal=False), nullable=False),
    sa.Column('inter_stop_min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_district'))
    )
    op.create_table('service_allowance',
    sa.Column('brand', sa.String(length=8), nullable=False),
    sa.Column('dock_type', sa.String(length=12), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('brand', 'dock_type', name=op.f('pk_service_allowance'))
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('temp', sa.String(length=8), nullable=False),
    sa.Column('weight_cap_kg', sa.Numeric(precision=8, scale=1, asdecimal=False), nullable=False),
    sa.Column('volume_cap_m3', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
    sa.Column('fuel_type', sa.String(length=12), nullable=False),
    sa.Column('km_per_l', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('weekly_fuel_quota_l', sa.Numeric(precision=7, scale=1, asdecimal=False), nullable=False),
    sa.Column('depot', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id', name=op.f('pk_vehicle'))
    )
    op.create_index(op.f('ix_vehicle_depot'), 'vehicle', ['depot'], unique=False)
    op.create_table('workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_anchor_real', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_anchor_sim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_rate', sa.Double(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace')),
    sa.UniqueConstraint('code', name=op.f('uq_workspace_code'))
    )
    op.create_table('outlet',
    sa.Column('outlet_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=False),
    sa.Column('brand', sa.String(length=8), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('depot', sa.String(length=16), nullable=False),
    sa.Column('dock_type', sa.String(length=12), nullable=False),
    sa.Column('parking_constraint', sa.String(length=12), nullable=False),
    sa.Column('mall_window', sa.String(length=11), nullable=True),
    sa.Column('window_open', sa.String(length=5), nullable=False),
    sa.Column('window_close', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['district'], ['district.name'], name=op.f('fk_outlet_district_district')),
    sa.PrimaryKeyConstraint('outlet_id', name=op.f('pk_outlet'))
    )
    op.create_index(op.f('ix_outlet_brand'), 'outlet', ['brand'], unique=False)
    op.create_index(op.f('ix_outlet_depot'), 'outlet', ['depot'], unique=False)
    op.create_index(op.f('ix_outlet_district'), 'outlet', ['district'], unique=False)
    op.create_table('road_condition',
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('disruption_index', sa.Numeric(precision=5, scale=1, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['district'], ['district.name'], name=op.f('fk_road_condition_district_district')),
    sa.PrimaryKeyConstraint('district', 'date', name=op.f('pk_road_condition'))
    )
    op.create_table('scheduled_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_scheduled_event_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_event'))
    )
    op.create_index(op.f('ix_scheduled_event_due_at'), 'scheduled_event', ['due_at'], unique=False)
    op.create_index(op.f('ix_scheduled_event_workspace_id'), 'scheduled_event', ['workspace_id'], unique=False)
    op.create_table('traffic_speed',
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('hour', sa.SmallInteger(), nullable=False),
    sa.Column('monsoon', sa.Boolean(), nullable=False),
    sa.Column('speed_index', sa.Numeric(precision=5, scale=1, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['district'], ['district.name'], name=op.f('fk_traffic_speed_district_district')),
    sa.PrimaryKeyConstraint('district', 'hour', 'monsoon', name=op.f('pk_traffic_speed'))
    )
    op.create_table('usual_run',
    sa.Column('vehicle_id', sa.String(length=8), nullable=False),
    sa.Column('dow_name', sa.String(length=3), nullable=False),
    sa.Column('trip_no', sa.SmallInteger(), nullable=False),
    sa.Column('brand', sa.String(length=8), nullable=False),
    sa.Column('temp', sa.String(length=8), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('share', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['district'], ['district.name'], name=op.f('fk_usual_run_district_district')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], name=op.f('fk_usual_run_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('vehicle_id', 'dow_name', 'trip_no', name=op.f('pk_usual_run'))
    )
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('dispatcher', 'loader', 'driver', 'store_manager', name='role', native_enum=False, length=24), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('pin_hash', sa.String(length=128), nullable=True),
    sa.Column('depot', sa.String(length=16), nullable=True),
    sa.Column('outlet_id', sa.String(length=8), nullable=True),
    sa.Column('vehicle_id', sa.String(length=8), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('judge_account', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], name=op.f('fk_app_user_outlet_id_outlet')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], name=op.f('fk_app_user_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_index(op.f('ix_app_user_role'), 'app_user', ['role'], unique=False)
    op.create_table('order_stream',
    sa.Column('dow_name', sa.String(length=3), nullable=False),
    sa.Column('outlet_id', sa.String(length=8), nullable=False),
    sa.Column('temp', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], name=op.f('fk_order_stream_outlet_id_outlet')),
    sa.PrimaryKeyConstraint('dow_name', 'outlet_id', 'temp', name=op.f('pk_order_stream'))
    )
    op.create_table('outlet_dwell',
    sa.Column('outlet_id', sa.String(length=8), nullable=False),
    sa.Column('monsoon', sa.Boolean(), nullable=False),
    sa.Column('p10', sa.Numeric(precision=6, scale=1, asdecimal=False), nullable=False),
    sa.Column('p50', sa.Numeric(precision=6, scale=1, asdecimal=False), nullable=False),
    sa.Column('p90', sa.Numeric(precision=6, scale=1, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], name=op.f('fk_outlet_dwell_outlet_id_outlet')),
    sa.PrimaryKeyConstraint('outlet_id', 'monsoon', name=op.f('pk_outlet_dwell'))
    )
    op.create_table('service_history',
    sa.Column('outlet_id', sa.String(length=8), nullable=False),
    sa.Column('temp', sa.String(length=8), nullable=False),
    sa.Column('last_delivered', sa.Date(), nullable=True),
    sa.Column('deferred_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], name=op.f('fk_service_history_outlet_id_outlet')),
    sa.PrimaryKeyConstraint('outlet_id', 'temp', name=op.f('pk_service_history'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_audit_log_actor_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_audit_log_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_table('delivery_order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_ref', sa.String(length=12), nullable=False),
    sa.Column('outlet_id', sa.String(length=8), nullable=False),
    sa.Column('brand', sa.String(length=8), nullable=False),
    sa.Column('temp', sa.String(length=8), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=9, scale=1, asdecimal=False), nullable=False),
    sa.Column('volume_m3', sa.Numeric(precision=9, scale=3, asdecimal=False), nullable=False),
    sa.Column('status', sa.Enum('received', 'allocated', 'deferred', 'loaded', 'on_the_way', 'delivered', 'failed', 'confirmed', 'disputed', name='orderstatus', native_enum=False, length=24), nullable=False),
    sa.Column('source', sa.Enum('store', 'seed', 'simulator', name='ordersource', native_enum=False, length=24), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('placed_by', sa.Uuid(), nullable=True),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], name=op.f('fk_delivery_order_outlet_id_outlet')),
    sa.ForeignKeyConstraint(['placed_by'], ['app_user.id'], name=op.f('fk_delivery_order_placed_by_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_delivery_order_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_order')),
    sa.UniqueConstraint('workspace_id', 'order_ref', name=op.f('uq_delivery_order_workspace_id'))
    )
    op.create_index(op.f('ix_delivery_order_outlet_id'), 'delivery_order', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_delivery_order_run_date'), 'delivery_order', ['run_date'], unique=False)
    op.create_index(op.f('ix_delivery_order_workspace_id'), 'delivery_order', ['workspace_id'], unique=False)
    op.create_table('device_contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_record_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_records', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_device_contact_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_device_contact_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_contact'))
    )
    op.create_index(op.f('ix_device_contact_user_id'), 'device_contact', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_contact_workspace_id'), 'device_contact', ['workspace_id'], unique=False)
    op.create_table('feed_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('shortfall', 'delay', 'failed_stop', 'problem', 'dispute', 'silence', 'conflict', name='feedkind', native_enum=False, length=24), nullable=False),
    sa.Column('depot', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handled_by', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['handled_by'], ['app_user.id'], name=op.f('fk_feed_item_handled_by_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_feed_item_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_item'))
    )
    op.create_index(op.f('ix_feed_item_created_at'), 'feed_item', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_item_workspace_id'), 'feed_item', ['workspace_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('outlet_id', sa.String(length=8), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('show_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], name=op.f('fk_notification_outlet_id_outlet')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_notification_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_notification_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_outlet_id'), 'notification', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_workspace_id'), 'notification', ['workspace_id'], unique=False)
    op.create_table('photo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], name=op.f('fk_photo_uploaded_by_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_photo_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo'))
    )
    op.create_index(op.f('ix_photo_workspace_id'), 'photo', ['workspace_id'], unique=False)
    op.create_table('plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('depot', sa.String(length=16), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='planstatus', native_enum=False, length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['app_user.id'], name=op.f('fk_plan_published_by_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_plan_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan')),
    sa.UniqueConstraint('workspace_id', 'depot', 'run_date', name=op.f('uq_plan_workspace_id'))
    )
    op.create_index(op.f('ix_plan_workspace_id'), 'plan', ['workspace_id'], unique=False)
    op.create_table('vehicle_day',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=8), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('available', 'workshop', 'standby', name='vehicledaystatus', native_enum=False, length=24), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('fuel_used_l', sa.Numeric(precision=7, scale=1, asdecimal=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['app_user.id'], name=op.f('fk_vehicle_day_driver_id_app_user')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], name=op.f('fk_vehicle_day_vehicle_id_vehicle')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_vehicle_day_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_day')),
    sa.UniqueConstraint('workspace_id', 'vehicle_id', 'run_date', name=op.f('uq_vehicle_day_workspace_id'))
    )
    op.create_index(op.f('ix_vehicle_day_workspace_id'), 'vehicle_day', ['workspace_id'], unique=False)
    op.create_table('deferral',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('capacity', 'cutoff', 'manual', name='deferralkind', native_enum=False, length=24), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('store_notice', sa.Text(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], name=op.f('fk_deferral_confirmed_by_app_user')),
    sa.ForeignKeyConstraint(['order_id'], ['delivery_order.id'], name=op.f('fk_deferral_order_id_delivery_order')),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_deferral_plan_id_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_deferral_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deferral'))
    )
    op.create_index(op.f('ix_deferral_order_id'), 'deferral', ['order_id'], unique=False)
    op.create_index(op.f('ix_deferral_workspace_id'), 'deferral', ['workspace_id'], unique=False)
    op.create_table('order_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=24), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('carried_qty', sa.Integer(), nullable=False),
    sa.Column('carried_from', sa.String(length=12), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_type'], ['case_type.code'], name=op.f('fk_order_line_case_type_case_type')),
    sa.ForeignKeyConstraint(['order_id'], ['delivery_order.id'], name=op.f('fk_order_line_order_id_delivery_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_order_line_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_line'))
    )
    op.create_index(op.f('ix_order_line_order_id'), 'order_line', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_line_workspace_id'), 'order_line', ['workspace_id'], unique=False)
    op.create_table('receipt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'with_issues', name='receiptstatus', native_enum=False, length=24), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('before_driver_proof', sa.Boolean(), nullable=False),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], name=op.f('fk_receipt_confirmed_by_app_user')),
    sa.ForeignKeyConstraint(['order_id'], ['delivery_order.id'], name=op.f('fk_receipt_order_id_delivery_order'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_receipt_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt')),
    sa.UniqueConstraint('order_id', name=op.f('uq_receipt_order_id'))
    )
    op.create_index(op.f('ix_receipt_workspace_id'), 'receipt', ['workspace_id'], unique=False)
    op.create_table('trip',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=8), nullable=False),
    sa.Column('trip_no', sa.SmallInteger(), nullable=False),
    sa.Column('brand', sa.String(length=8), nullable=False),
    sa.Column('temp', sa.String(length=8), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('planned_depart', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_back', sa.DateTime(timezone=True), nullable=False),
    sa.Column('std_minutes', sa.Integer(), nullable=False),
    sa.Column('fuel_l', sa.Numeric(precision=7, scale=1, asdecimal=False), nullable=False),
    sa.Column('status', sa.Enum('planned', 'loading', 'loaded', 'departed', 'finished', 'cancelled', name='tripstatus', native_enum=False, length=24), nullable=False),
    sa.Column('is_backup', sa.Boolean(), nullable=False),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_back', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['district'], ['district.name'], name=op.f('fk_trip_district_district')),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_trip_plan_id_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], name=op.f('fk_trip_vehicle_id_vehicle')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_trip_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip'))
    )
    op.create_index(op.f('ix_trip_plan_id'), 'trip', ['plan_id'], unique=False)
    op.create_index(op.f('ix_trip_vehicle_id'), 'trip', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_trip_workspace_id'), 'trip', ['workspace_id'], unique=False)
    op.create_table('handover',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('planned_cases', sa.Integer(), nullable=False),
    sa.Column('loaded_cases', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.Uuid(), nullable=True),
    sa.Column('accepted_on', sa.String(length=8), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['app_user.id'], name=op.f('fk_handover_accepted_by_app_user')),
    sa.ForeignKeyConstraint(['completed_by'], ['app_user.id'], name=op.f('fk_handover_completed_by_app_user')),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_handover_trip_id_trip'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_handover_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handover')),
    sa.UniqueConstraint('trip_id', name=op.f('uq_handover_trip_id'))
    )
    op.create_index(op.f('ix_handover_workspace_id'), 'handover', ['workspace_id'], unique=False)
    op.create_table('plan_change',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_plan_change_created_by_app_user')),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_plan_change_plan_id_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_plan_change_trip_id_trip'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_plan_change_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_change'))
    )
    op.create_index(op.f('ix_plan_change_plan_id'), 'plan_change', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_change_workspace_id'), 'plan_change', ['workspace_id'], unique=False)
    op.create_table('receipt_issue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('case_type', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.Enum('missing', 'damaged', 'not_cold', name='issuekind', native_enum=False, length=24), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_type'], ['case_type.code'], name=op.f('fk_receipt_issue_case_type_case_type')),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('fk_receipt_issue_photo_id_photo')),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], name=op.f('fk_receipt_issue_receipt_id_receipt'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_receipt_issue_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_issue'))
    )
    op.create_index(op.f('ix_receipt_issue_receipt_id'), 'receipt_issue', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_receipt_issue_workspace_id'), 'receipt_issue', ['workspace_id'], unique=False)
    op.create_table('stop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('outlet_id', sa.String(length=8), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'arrived', 'delivered', 'failed', 'moved', 'cancelled', name='stopstatus', native_enum=False, length=24), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('backup_of', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['backup_of'], ['stop.id'], name=op.f('fk_stop_backup_of_stop')),
    sa.ForeignKeyConstraint(['order_id'], ['delivery_order.id'], name=op.f('fk_stop_order_id_delivery_order')),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], name=op.f('fk_stop_outlet_id_outlet')),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_stop_trip_id_trip'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_stop_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stop'))
    )
    op.create_index(op.f('ix_stop_order_id'), 'stop', ['order_id'], unique=False)
    op.create_index(op.f('ix_stop_trip_id'), 'stop', ['trip_id'], unique=False)
    op.create_index(op.f('ix_stop_workspace_id'), 'stop', ['workspace_id'], unique=False)
    op.create_table('conflict',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('backup_stop_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('waiting_for_driver', 'resolved', name='conflictstatus', native_enum=False, length=24), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.String(length=8), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['backup_stop_id'], ['stop.id'], name=op.f('fk_conflict_backup_stop_id_stop'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['app_user.id'], name=op.f('fk_conflict_driver_id_app_user')),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], name=op.f('fk_conflict_stop_id_stop'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_conflict_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflict'))
    )
    op.create_index(op.f('ix_conflict_stop_id'), 'conflict', ['stop_id'], unique=False)
    op.create_index(op.f('ix_conflict_workspace_id'), 'conflict', ['workspace_id'], unique=False)
    op.create_table('field_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('load_accepted', 'departed', 'arrived', 'delivered', 'failed', 'problem', 'trip_finished', 'checkin', name='fieldeventkind', native_enum=False, length=24), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('stop_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=True),
    sa.Column('accuracy_m', sa.Numeric(precision=7, scale=1, asdecimal=False), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.Enum('applied', 'duplicate', 'conflict', 'rejected', name='fieldeventoutcome', native_enum=False, length=24), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], name=op.f('fk_field_event_stop_id_stop'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_field_event_trip_id_trip'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_field_event_user_id_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_field_event_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_event'))
    )
    op.create_index(op.f('ix_field_event_stop_id'), 'field_event', ['stop_id'], unique=False)
    op.create_index(op.f('ix_field_event_trip_id'), 'field_event', ['trip_id'], unique=False)
    op.create_index(op.f('ix_field_event_user_id'), 'field_event', ['user_id'], unique=False)
    op.create_index(op.f('ix_field_event_workspace_id'), 'field_event', ['workspace_id'], unique=False)
    op.create_table('load_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('case_type', sa.String(length=24), nullable=False),
    sa.Column('load_order', sa.SmallInteger(), nullable=False),
    sa.Column('planned_qty', sa.Integer(), nullable=False),
    sa.Column('loaded_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('to_load', 'in_progress', 'checked', 'flag_waiting', 'decided', name='loadlinestatus', native_enum=False, length=24), nullable=False),
    sa.Column('changed_by_plan', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_type'], ['case_type.code'], name=op.f('fk_load_line_case_type_case_type')),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], name=op.f('fk_load_line_stop_id_stop'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_load_line_trip_id_trip'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_load_line_updated_by_app_user')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_load_line_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_line'))
    )
    op.create_index(op.f('ix_load_line_stop_id'), 'load_line', ['stop_id'], unique=False)
    op.create_index(op.f('ix_load_line_trip_id'), 'load_line', ['trip_id'], unique=False)
    op.create_index(op.f('ix_load_line_workspace_id'), 'load_line', ['workspace_id'], unique=False)
    op.create_table('problem_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Enum('delayed', 'outlet_closed', 'access_blocked', 'goods_refused', 'damaged_in_transit', 'vehicle_problem', name='problemreason', native_enum=False, length=24), nullable=False),
    sa.Column('delay_min', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['field_event.id'], name=op.f('fk_problem_report_event_id_field_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], name=op.f('fk_problem_report_stop_id_stop'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name=op.f('fk_problem_report_trip_id_trip'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_problem_report_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_report'))
    )
    op.create_index(op.f('ix_problem_report_trip_id'), 'problem_report', ['trip_id'], unique=False)
    op.create_index(op.f('ix_problem_report_workspace_id'), 'problem_report', ['workspace_id'], unique=False)
    op.create_table('proof',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_name', sa.String(length=64), nullable=False),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('all_delivered', sa.Boolean(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('signature_svg', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['field_event.id'], name=op.f('fk_proof_event_id_field_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('fk_proof_photo_id_photo')),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], name=op.f('fk_proof_stop_id_stop'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_proof_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof')),
    sa.UniqueConstraint('stop_id', name=op.f('uq_proof_stop_id'))
    )
    op.create_index(op.f('ix_proof_workspace_id'), 'proof', ['workspace_id'], unique=False)
    op.create_table('shortfall',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('load_line_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('missing', 'damaged', name='shortfallkind', native_enum=False, length=24), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flagged_by', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('send_short', 'wait_for_stock', name='shortfalldecision', native_enum=False, length=24), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('added_to_order_ref', sa.String(length=12), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['app_user.id'], name=op.f('fk_shortfall_decided_by_app_user')),
    sa.ForeignKeyConstraint(['flagged_by'], ['app_user.id'], name=op.f('fk_shortfall_flagged_by_app_user')),
    sa.ForeignKeyConstraint(['load_line_id'], ['load_line.id'], name=op.f('fk_shortfall_load_line_id_load_line'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('fk_shortfall_photo_id_photo')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_shortfall_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortfall'))
    )
    op.create_index(op.f('ix_shortfall_load_line_id'), 'shortfall', ['load_line_id'], unique=False)
    op.create_index(op.f('ix_shortfall_workspace_id'), 'shortfall', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortfall_workspace_id'), table_name='shortfall')
    op.drop_index(op.f('ix_shortfall_load_line_id'), table_name='shortfall')
    op.drop_table('shortfall')
    op.drop_index(op.f('ix_proof_workspace_id'), table_name='proof')
    op.drop_table('proof')
    op.drop_index(op.f('ix_problem_report_workspace_id'), table_name='problem_report')
    op.drop_index(op.f('ix_problem_report_trip_id'), table_name='problem_report')
    op.drop_table('problem_report')
    op.drop_index(op.f('ix_load_line_workspace_id'), table_name='load_line')
    op.drop_index(op.f('ix_load_line_trip_id'), table_name='load_line')
    op.drop_index(op.f('ix_load_line_stop_id'), table_name='load_line')
    op.drop_table('load_line')
    op.drop_index(op.f('ix_field_event_workspace_id'), table_name='field_event')
    op.drop_index(op.f('ix_field_event_user_id'), table_name='field_event')
    op.drop_index(op.f('ix_field_event_trip_id'), table_name='field_event')
    op.drop_index(op.f('ix_field_event_stop_id'), table_name='field_event')
    op.drop_table('field_event')
    op.drop_index(op.f('ix_conflict_workspace_id'), table_name='conflict')
    op.drop_index(op.f('ix_conflict_stop_id'), table_name='conflict')
    op.drop_table('conflict')
    op.drop_index(op.f('ix_stop_workspace_id'), table_name='stop')
    op.drop_index(op.f('ix_stop_trip_id'), table_name='stop')
    op.drop_index(op.f('ix_stop_order_id'), table_name='stop')
    op.drop_table('stop')
    op.drop_index(op.f('ix_receipt_issue_workspace_id'), table_name='receipt_issue')
    op.drop_index(op.f('ix_receipt_issue_receipt_id'), table_name='receipt_issue')
    op.drop_table('receipt_issue')
    op.drop_index(op.f('ix_plan_change_workspace_id'), table_name='plan_change')
    op.drop_index(op.f('ix_plan_change_plan_id'), table_name='plan_change')
    op.drop_table('plan_change')
    op.drop_index(op.f('ix_handover_workspace_id'), table_name='handover')
    op.drop_table('handover')
    op.drop_index(op.f('ix_trip_workspace_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_vehicle_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_plan_id'), table_name='trip')
    op.drop_table('trip')
    op.drop_index(op.f('ix_receipt_workspace_id'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_order_line_workspace_id'), table_name='order_line')
    op.drop_index(op.f('ix_order_line_order_id'), table_name='order_line')
    op.drop_table('order_line')
    op.drop_index(op.f('ix_deferral_workspace_id'), table_name='deferral')
    op.drop_index(op.f('ix_deferral_order_id'), table_name='deferral')
    op.drop_table('deferral')
    op.drop_index(op.f('ix_vehicle_day_workspace_id'), table_name='vehicle_day')
    op.drop_table('vehicle_day')
    op.drop_index(op.f('ix_plan_workspace_id'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_photo_workspace_id'), table_name='photo')
    op.drop_table('photo')
    op.drop_index(op.f('ix_notification_workspace_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_outlet_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_feed_item_workspace_id'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_created_at'), table_name='feed_item')
    op.drop_table('feed_item')
    op.drop_index(op.f('ix_device_contact_workspace_id'), table_name='device_contact')
    op.drop_index(op.f('ix_device_contact_user_id'), table_name='device_contact')
    op.drop_table('device_contact')
    op.drop_index(op.f('ix_delivery_order_workspace_id'), table_name='delivery_order')
    op.drop_index(op.f('ix_delivery_order_run_date'), table_name='delivery_order')
    op.drop_index(op.f('ix_delivery_order_outlet_id'), table_name='delivery_order')
    op.drop_table('delivery_order')
    op.drop_index(op.f('ix_audit_log_workspace_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('service_history')
    op.drop_table('outlet_dwell')
    op.drop_table('order_stream')
    op.drop_index(op.f('ix_app_user_role'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('usual_run')
    op.drop_table('traffic_speed')
    op.drop_index(op.f('ix_scheduled_event_workspace_id'), table_name='scheduled_event')
    op.drop_index(op.f('ix_scheduled_event_due_at'), table_name='scheduled_event')
    op.drop_table('scheduled_event')
    op.drop_table('road_condition')
    op.drop_index(op.f('ix_outlet_district'), table_name='outlet')
    op.drop_index(op.f('ix_outlet_depot'), table_name='outlet')
    op.drop_index(op.f('ix_outlet_brand'), table_name='outlet')
    op.drop_table('outlet')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_vehicle_depot'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_table('service_allowance')
    op.drop_table('district')
    op.drop_table('case_type')
    op.drop_table('calendar_day')
    # ### end Alembic commands ###
