"""Usual stores per vehicle run

Revision ID: 27aea4acb656
Revises: ff584073c694
Create Date: 2026-09-30 18:36:10.662651+05:30
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '27aea4acb656'
down_revision: str | None = 'ff584073c694'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usual_stop',
    sa.Column('vehicle_id', sa.String(length=8), nullable=False),
    sa.Column('dow_name', sa.String(length=3), nullable=False),
    sa.Column('trip_no', sa.SmallInteger(), nullable=False),
    sa.Column('brand', sa.String(length=8), nullable=False),
    sa.Column('temp', sa.String(length=8), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('outlet_id', sa.String(length=8), nullable=False),
    sa.Column('share', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=False),
    sa.Column('run_share', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['district'], ['district.name'], name=op.f('fk_usual_stop_district_district')),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.outlet_id'], name=op.f('fk_usual_stop_outlet_id_outlet')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], name=op.f('fk_usual_stop_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('vehicle_id', 'dow_name', 'trip_no', 'brand', 'temp', 'district', 'outlet_id', name=op.f('pk_usual_stop'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usual_stop')
    # ### end Alembic commands ###
