"""All tables. Importing this module registers every model on Base.metadata (Alembic relies on it)."""

from relay_api.models.base import Base, WorkspaceScoped
from relay_api.models.comms import FeedItem, FeedKind, Notification
from relay_api.models.dock import (
    Handover,
    LoadLine,
    LoadLineStatus,
    Shortfall,
    ShortfallDecision,
    ShortfallKind,
)
from relay_api.models.field import (
    Conflict,
    ConflictStatus,
    DeviceContact,
    FieldEvent,
    FieldEventKind,
    FieldEventOutcome,
    Photo,
    ProblemReason,
    ProblemReport,
    Proof,
)
from relay_api.models.orders import Order, OrderLine, OrderSource, OrderStatus
from relay_api.models.people import AppUser, Role
from relay_api.models.planning import (
    Deferral,
    DeferralKind,
    Plan,
    PlanChange,
    PlanStatus,
    Stop,
    StopStatus,
    Trip,
    TripStatus,
    VehicleDay,
    VehicleDayStatus,
)
from relay_api.models.reference import (
    CalendarDay,
    CaseType,
    District,
    OrderStream,
    Outlet,
    OutletDwell,
    RoadCondition,
    ServiceAllowance,
    ServiceHistory,
    TrafficSpeed,
    UsualRun,
    UsualStop,
    Vehicle,
)
from relay_api.models.store import IssueKind, Receipt, ReceiptIssue, ReceiptStatus
from relay_api.models.workspace import AuditLog, ScheduledEvent, Workspace

__all__ = [
    "AppUser",
    "AuditLog",
    "Base",
    "CalendarDay",
    "CaseType",
    "Conflict",
    "ConflictStatus",
    "Deferral",
    "DeferralKind",
    "DeviceContact",
    "District",
    "FeedItem",
    "FeedKind",
    "FieldEvent",
    "FieldEventKind",
    "FieldEventOutcome",
    "Handover",
    "IssueKind",
    "LoadLine",
    "LoadLineStatus",
    "Notification",
    "Order",
    "OrderLine",
    "OrderSource",
    "OrderStatus",
    "OrderStream",
    "Outlet",
    "OutletDwell",
    "Photo",
    "Plan",
    "PlanChange",
    "PlanStatus",
    "ProblemReason",
    "ProblemReport",
    "Proof",
    "Receipt",
    "ReceiptIssue",
    "ReceiptStatus",
    "RoadCondition",
    "Role",
    "ScheduledEvent",
    "ServiceAllowance",
    "ServiceHistory",
    "Shortfall",
    "ShortfallDecision",
    "ShortfallKind",
    "Stop",
    "StopStatus",
    "TrafficSpeed",
    "Trip",
    "TripStatus",
    "UsualRun",
    "UsualStop",
    "Vehicle",
    "VehicleDay",
    "VehicleDayStatus",
    "Workspace",
    "WorkspaceScoped",
]
